sudo: required

services:
  - docker

jobs:
  include:
    - stage: "Pre-build"
      script: 
        - docker build -t integr8/alpine-asciidoctor-helper .
        - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin
        - docker push integr8/alpine-asciidoctor-helper
    - stage: "Publish docs"
      script:
        - docker run --rm -v $TRAVIS_BUILD_DIR/output:/documents/ integr8/alpine-asciidoctor-helper asciidoctor docs/index.adoc
      deploy:
        provider: pages
        target-branch: gh-pages
        skip_cleanup: true
        local_dir: output/
        github_token: $GH_TOKEN
        on:
          branch: development
