ASCIIDOCTOR_HTML_OPTIONS=''

if [[ -z "${ASCIIDOCTOR_HTML_THEME}"]]; then
  if [[ -f ${ASCIIDOCTOR_THEMES_PATH}/${ASCIIDOCTOR_HTML_THEME}.css ]]; then
    ASCIIDOCTOR_HTML_OPTIONS="${ASCIIDOCTOR_HTML_OPTIONS} -a stylesheet=${ASCIIDOCTOR_THEMES_PATH}/${ASCIIDOCTOR_HTML_THEME}.css"
  else
    echo "The theme ${ASCIIDOCTOR_THEMES_PATH}/${ASCIIDOCTOR_HTML_THEME}.css doesnt exists!"
    exit 0
  fi
fi

echo "${@:2}"
asciidoctor -D $ASCIIDOCTOR_OUTPUT_PATH $ASCIIDOCTOR_HTML_OPTIONS "${@:2}"