#!/bin/bash
DEFAULT_RESOURCES_DIR=$(dirname $(gem which asciidoctor-pdf))

: ${ASCIIDOCTOR_PDF_THEMES_DIR:=${DEFAULT_RESOURCES_DIR/%lib/data}/themes}
: ${ASCIIDOCTOR_PDF_FONTS_DIR:=${DEFAULT_RESOURCES_DIR/%lib/data}/fonts}

ASCIIDOCTOR_PDF_OPTIONS=""

if [[ ! -z "${ASCIIDOCTOR_PDF_THEMES_DIR}" ]]; then
  if [[ -d "${ASCIIDOCTOR_PDF_THEMES_DIR}" ]]; then
    ASCIIDOCTOR_PDF_OPTIONS="${ASCIIDOCTOR_PDF_OPTIONS} -a pdf-stylesdir=${ASCIIDOCTOR_PDF_THEMES_DIR}"
  fi
fi

if [[ ! -z "${ASCIIDOCTOR_PDF_THEME}" ]]; then
  ASCIIDOCTOR_PDF_OPTIONS="${ASCIIDOCTOR_PDF_OPTIONS} -a pdf-style=${ASCIIDOCTOR_PDF_THEME}"
fi

if [[ ! -z "${ASCIIDOCTOR_PDF_FONTS_DIR}" ]]; then
  ASCIIDOCTOR_PDF_OPTIONS="${ASCIIDOCTOR_PDF_OPTIONS} -a pdf-fontsdir=${ASCIIDOCTOR_PDF_FONTS_DIR}"
fi
 
asciidoctor-pdf -D $ASCIIDOCTOR_OUTPUT_PATH $ASCIIDOCTOR_PLUGIN_OPTIONS $ASCIIDOCTOR_PDF_OPTIONS "${@:2}"